name: core_data
description: A new Flutter module project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <3.10.0'

dependencies:
  flutter:
    sdk: flutter

  common_dependencies:
    path: '../common_dependencies'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5 


flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.core_data
    iosBundleIdentifier: com.example.coreData
