name: feature_currency_details
description: A new Flutter module project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core_module:
    path: '../core_module'

  common_dependencies:
    path: '../common_dependencies'
  core_data:
    path: '../core_data'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5 


flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.feature_currency_details
    iosBundleIdentifier: com.example.featureCurrencyDetails
